[package]
name = "url_balancing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7"
rand = "0.8"
redis = { version = "0.27.3", features = ["tokio-comp"] }
lazy_static = "1.4"
tokio = { version = "1", features = ["full"] }
tower = { version = "0.5", features = ["full"] }
tower-http = "0.6"
serde = { version = "1.0", features = ["derive"] }
axum-macros = "0.4.2"
[dev-dependencies]
reqwest = "0.12"
